services:
  redmine:
    image: redmine:circle
    build:
      context: .
    container_name: redmine.local
    ports:
      - "80:3000"
    volumes:
      - app_data:/usr/src/redmine/files
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: Aa123456
      REDMINE_DB_DATABASE: redmine
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db.redmine.local
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: redmine
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  app_data:
